project:
  type: website
  output-dir: _site

website:
  sidebar:
    style: "docked"
    search: true
    collapse-level: 2
    title: "Datacubes"
    tools:
      - icon: github
        href: https://github.com/pangeo-data/datacube-worst-practices
        text: "Repo"
    contents:
      - href: index.qmd
        text: Home

format:

  html:
    theme:
      light: [cosmo, theme.scss] # from https://github.com/sta210-s22/website/blob/main/_quarto.yml
      dark: [cosmo, theme-dark.scss]
    code-copy: true
    code-overflow: wrap
    css: styles.css
filters:
  - quarto
